# Site settings
title: Brien Dieterle
description: "Artist and Illustrator"
baseurl: ""
url: "https://briendieterle.com"
twitter_username: briendieterle
github_username:  briend

remote_theme: "mmistakes/minimal-mistakes@4.18.1"

plugins:
  - jekyll-include-cache
  


