# Site settings
title: Brien Dieterle
description: "Artist and Illustrator"
baseurl: ""
url: "https://briendieterle.com"
twitter_username: briendieterle
github_username:  briend

flickr:
  screen_name: Brien Dieterle

  

theme: jekyll-theme-cayman
